'use strict';
// The existing JSON control recordings remain the source of truth. Commit the
// generated module too, so both file:// source play and the offline bundle work.
const fs = require('node:fs'), path = require('node:path');
const ROOT = path.resolve(__dirname, '..');
function source(root = ROOT) {
    const files = ['tests/exposed-crosscurrent-controls.json', 'tests/fixtures/first-crossing-controls.json', 'tests/fixtures/bigger-boat-controls.json'];
    const runs = files.map(file => ({ ...JSON.parse(fs.readFileSync(path.join(root, file), 'utf8')), source: file }));
    return `/* Generated by tools/sync-replays.cjs from the checked-in control recordings. */\n(function (root) {\n    'use strict';\n    const runs = ${JSON.stringify(runs, null, 4)};\n    for (const run of runs) {\n        run.events.forEach(Object.freeze);\n        Object.freeze(run.events);\n        Object.freeze(run);\n    }\n    const api = Object.freeze({ step: 1 / 120, runs: Object.freeze(runs) });\n    if (typeof module !== 'undefined' && module.exports) module.exports = api;\n    root.HarborVerification = api;\n})(typeof globalThis !== 'undefined' ? globalThis : this);\n`;
}
if (require.main === module) {
    fs.writeFileSync(path.join(ROOT, 'src/verification.js'), source());
    console.log('Synchronized browser verification recordings.');
}
module.exports = { source };
