(function(root) {
    'use strict';
    const wagon=(id,edge,s,extra={})=>({id,edge,s,length:16,mass:42000,...extra});
    const loco=(edge,s)=>wagon('engine',edge,s,{length:20,mass:80000,powered:true,name:'No. 17'});
    const level=(id,name,brief,tip,world,rail,pace)=>({id,name,brief,tip,world,rail,pace,
        kind:'Freight railway',start:[100,100,0],berth:{x:100,y:100,a:0,l:50,w:20,angle:10,speed:.2},
        spec:{name:'No. 17',length:20,beam:4,mass:80000},standalone:true});
    const levels=[
        level('long-grade-1','The Last Wagon Counts',
            'Stop at the receiving board using the locomotive brake. Collect the two waiting wagons, then reverse clear of the junction and put the complete train in Quarry Siding.',
            'Couple below 2 km/h. Release the waiting wagons’ handbrakes after coupling. The junction lamp stays red until the last wagon clears.',
            [1100,650],{
                thermal:false,scenery:'quarry',
                nodes:{q:[90,465,18],j:[460,420,17],r:[990,470,17],s:[770,130,20]},
                tracks:[
                    {id:'approach',a:'q',b:'j',points:[[90,465,18],[240,485,18],[370,445,17],[460,420,17]],limit:10},
                    {id:'receiving',a:'j',b:'r',points:[[460,420,17],[650,380,17],[820,400,17],[990,470,17]],limit:7},
                    {id:'siding',a:'j',b:'s',points:[[460,420,17],[530,300,18],[650,200,19],[770,130,20]],limit:6}
                ],
                switches:[{node:'j',label:'Quarry Junction',stem:'approach',branches:['receiving','siding'],names:['Receiving yard','Quarry Siding']}],
                groups:[{cars:[loco('approach',230),wagon('Q1','approach',210.8),wagon('Q2','approach',193.6)]},
                    {secured:true,cars:[wagon('R1','receiving',201.2),wagon('R2','receiving',184)]}],
                zones:[{id:'board',name:'Receiving board',edge:'receiving',from:95,to:145,color:'#e0bd6c'},
                    {id:'final',name:'Quarry Siding',edge:'siding',from:65,to:290,color:'#82b99b'}],
                tasks:[{id:'first-stop',type:'stop',zone:'board',independent:true,text:'Stop at the receiving board'},
                    {id:'collect',type:'coupled',cars:['R1','R2'],after:'first-stop',text:'Collect both waiting wagons'},
                    {id:'park',type:'park',zone:'final',cars:['engine','Q1','Q2','R1','R2'],after:'collect',text:'Whole train in Quarry Siding, handbrakes set'}]
            },[300,480,750]),
        level('long-grade-2','Head at the Wrong End',
            'Push the blue wagons into the mill siding and leave them secured. The orange wagons belong in the foundry siding at the other end. Run the engine around them before the second push.',
            'Select a wagon to set its cut’s handbrakes. Uncouple using a link in the train strip. The short loop has room for the engine, not the whole freight.',
            [1050,680],{
                thermal:false,scenery:'yard',
                nodes:{west:[70,350,12],a:[245,350,12],w:[400,350,12],e:[550,350,12],b:[760,350,12],east:[990,350,12],mill:[150,610,15],foundry:[900,90,15]},
                tracks:[
                    {id:'west-head',a:'west',b:'a',limit:6},
                    {id:'west-neck',a:'a',b:'w',limit:6},
                    {id:'main',a:'w',b:'e',points:[[400,350,12],[380,455,11],[470,520,10.4],[570,455,11],[550,350,12]],limit:6},
                    {id:'loop',a:'w',b:'e',points:[[400,350,12],[440,335,12],[510,335,12],[550,350,12]],limit:5},
                    {id:'east-neck',a:'e',b:'b',limit:6},
                    {id:'east-head',a:'b',b:'east',limit:6},
                    {id:'mill',a:'a',b:'mill',points:[[245,350,12],[210,460,13],[150,610,15]],limit:4},
                    {id:'foundry',a:'b',b:'foundry',points:[[760,350,12],[805,210,13],[900,90,15]],limit:4}
                ],
                switches:[
                    {node:'a',label:'Mill points',stem:'west-neck',branches:['west-head','mill'],names:['West headshunt','Mill siding']},
                    {node:'w',label:'West loop',stem:'west-neck',branches:['main','loop'],names:['Station road','Run-around']},
                    {node:'e',label:'East loop',stem:'east-neck',branches:['main','loop'],names:['Station road','Run-around']},
                    {node:'b',label:'Foundry points',stem:'east-neck',branches:['east-head','foundry'],names:['East headshunt','Foundry siding']}
                ],
                groups:[{cars:[loco('main',320),...['F1','F2','F3','F4','M1','M2'].map((id,i)=>wagon(id,'main',296.8-i*25.2,{length:24,mass:35000,destination:id[0]==='M'?'mill':'foundry'}))]}],
                zones:[{id:'mill-yard',name:'Mill · blue wagons',edge:'mill',from:50,to:230,color:'#79b9cd'},
                    {id:'foundry-yard',name:'Foundry · orange wagons',edge:'foundry',from:55,to:265,color:'#d89763'}],
                tasks:[{id:'mill-load',type:'delivery',zone:'mill-yard',cars:['M1','M2'],text:'Blue wagons secured at the mill; engine detached'},
                    {id:'foundry-load',type:'delivery',zone:'foundry-yard',cars:['F1','F2','F3','F4'],text:'Orange wagons secured at the foundry; engine detached'}]
            },[650,1000,1500]),
        level('long-grade-3','Stone Runs Downhill',
            'Bring the stone freight down to the valley works. The direct descent has tight bends; the eastern branch is longer and gentler. Both lead to a cooling loop above the works.',
            'Choose your route at both ends of each branch. Watch the tail’s grade and brake temperature. A cool train with room to stop is worth the extra distance.',
            [1750,1250],{
                thermal:true,scenery:'valley',
                nodes:{quarry:[100,140,62],summit:[500,140,60],join:[950,790,27],cool:[1090,905,25],out:[1270,1020,23],works:[1620,1130,22]},
                tracks:[
                    {id:'plateau',a:'quarry',b:'summit',limit:15},
                    {id:'steep',a:'summit',b:'join',points:[[500,140,60],[640,255,57],[715,390,48],[665,535,41],[770,665,33],[950,790,27]],limit:13,restrictions:[{from:.24,to:.63,limit:5.5}]},
                    {id:'gentle',a:'summit',b:'join',points:[[500,140,60],[970,90,54],[1450,240,46],[1460,600,36],[1230,735,30],[950,790,27]],limit:10},
                    {id:'valley',a:'join',b:'cool',limit:8},
                    {id:'direct',a:'cool',b:'out',limit:7},
                    {id:'cooling',a:'cool',b:'out',points:[[1090,905,25],[920,1010,24.5],[700,985,24],[660,1140,23.8],[980,1190,23.5],[1270,1020,23]],limit:7},
                    {id:'works-road',a:'out',b:'works',limit:5}
                ],
                switches:[{node:'summit',label:'Summit',stem:'plateau',branches:['steep','gentle'],names:['Direct descent','Eastern branch']},
                    {node:'join',label:'Valley Junction',stem:'valley',branches:['steep','gentle'],names:['Direct descent','Eastern branch']},
                    {node:'cool',label:'Loop entrance',stem:'valley',branches:['direct','cooling'],names:['Works approach','Cooling loop']},
                    {node:'out',label:'Works Junction',stem:'works-road',branches:['direct','cooling'],names:['Works approach','Cooling loop']}],
                groups:[{cars:[loco('plateau',270),...Array.from({length:10},(_,i)=>wagon('S'+(i+1),'plateau',250.8-i*17.2,{mass:65000}))]}],
                zones:[{id:'works-yard',name:'Valley works',edge:'works-road',from:35,to:345,color:'#82b99b'}],
                tasks:[{id:'stone',type:'park',zone:'works-yard',cars:['engine',...Array.from({length:10},(_,i)=>'S'+(i+1))],text:'All stone wagons inside the works, handbrakes set'}]
            },[450,650,950]),
        level('long-grade-4','Meet at Rook’s Hollow',
            'An opposing passenger service is due through the valley. Meet it at Rook’s Hollow, then bring the complete freight into East Yard.',
            'Rook’s loop fits the freight. The short refuge fits only the engine and a small cut. Clear both points before the passenger can pass; its signals and departure clock are visible.',
            [2200,850],{
                scenery:'valley',thermal:false,
                nodes:{west:[80,450,20],a:[570,450,20],b:[1090,450,20],c:[1460,450,18],d:[1590,450,18],east:[2130,450,18]},
                tracks:[{id:'west-road',a:'west',b:'a',limit:10},
                    {id:'hollow-main',a:'a',b:'b',limit:10},
                    {id:'hollow-loop',a:'a',b:'b',points:[[570,450,20],[680,590,20],[960,590,20],[1090,450,20]],limit:6},
                    {id:'valley-road',a:'b',b:'c',limit:10},
                    {id:'refuge-main',a:'c',b:'d',limit:10},
                    {id:'refuge-loop',a:'c',b:'d',points:[[1460,450,18],[1500,370,18],[1560,370,18],[1590,450,18]],limit:5},
                    {id:'east-road',a:'d',b:'east',limit:8}],
                switches:[{node:'a',label:'Rook west',stem:'west-road',branches:['hollow-main','hollow-loop'],names:['Main line','Rook’s loop']},
                    {node:'b',label:'Rook east',stem:'valley-road',branches:['hollow-main','hollow-loop'],names:['Main line','Rook’s loop']},
                    {node:'c',label:'Refuge west',stem:'valley-road',branches:['refuge-main','refuge-loop'],names:['Main line','Short refuge']},
                    {node:'d',label:'Refuge east',stem:'east-road',branches:['refuge-main','refuge-loop'],names:['Main line','Short refuge']}],
                groups:[{cars:[loco('west-road',365),...Array.from({length:12},(_,i)=>wagon('H'+(i+1),'west-road',339.8-i*29.2,{length:28,mass:32000}))]}],
                traffic:[{id:'passenger',name:'Valley passenger',depart:210,speed:7,timetable:'Departs 3:30 · Rook’s Hollow due 5:55',route:[['east-road',-1],['refuge-main',-1],['valley-road',-1],['hollow-main',-1],['west-road',-1]],head:125,length:110}],
                zones:[{id:'hollow',name:'Rook’s Hollow · full freight',edge:'hollow-loop',from:30,to:590},
                    {id:'refuge',name:'Short refuge · engine + cut',edge:'refuge-loop',from:22,to:170},
                    {id:'east-yard',name:'East Yard',edge:'east-road',from:35,to:505}],
                tasks:[{id:'meet',type:'traffic',traffic:'passenger',text:'Let the passenger clear the valley'},
                    {id:'freight',type:'park',after:'meet',zone:'east-yard',cars:['engine',...Array.from({length:12},(_,i)=>'H'+(i+1))],text:'Whole freight in East Yard, handbrakes set'}]
            },[650,900,1300]),
        level('long-grade-5','Three Wagons Going Somewhere',
            'Three stone wagons are running toward a broken river crossing. Catch them from the service line, couple below 2 km/h relative speed, and stop in the bridge approach.',
            'The early connection gives more stopping room. The longer service branch reaches a second interception on a gentler grade. The gravel catch siding saves the wagons, but the finish will be rough.',
            [2300,1000],{
                scenery:'valley',thermal:false,
                river:[[2120,0],[2070,190],[2160,400],[2140,650],[2220,1000]],
                nodes:{top:[80,290,27],early:[650,400,24],late:[1390,400,23],fork:[1740,400,22.5],broken:[2200,400,22.5],service:[270,680,24],catch:[1910,780,24]},
                tracks:[{id:'runaway-road',a:'top',b:'early',limit:18},
                    {id:'main-descent',a:'early',b:'late',points:[[650,400,24],[920,390,21.5],[1160,400,22.5],[1390,400,23]],limit:16},
                    {id:'service',a:'service',b:'early',limit:12},
                    {id:'service-long',a:'service',b:'late',points:[[270,680,24],[800,790,23],[1260,650,23],[1390,400,23]],limit:12},
                    {id:'bridge-road',a:'late',b:'fork',limit:12},
                    {id:'bridge-approach',a:'fork',b:'broken',limit:10,closedFrom:410},
                    {id:'catch',a:'fork',b:'catch',limit:14,catchFrom:120}],
                switches:[{node:'service',label:'Service fork',stem:'service',branches:['service-long'],names:['Later interception']},
                    {node:'early',label:'Early interception',stem:'main-descent',branches:['runaway-road','service'],names:['Quarry line','Service line']},
                    {node:'late',label:'Late interception',stem:'bridge-road',branches:['main-descent','service-long'],names:['Main descent','Long service line']},
                    {node:'fork',label:'Bridge points',stem:'bridge-road',branches:['bridge-approach','catch'],names:['Bridge approach','Emergency catch']}],
                groups:[{cars:[loco('service',180)]},{brake:0,speed:2.8,cars:[wagon('R1','runaway-road',300,{mass:65000}),wagon('R2','runaway-road',282.8,{mass:65000}),wagon('R3','runaway-road',265.6,{mass:65000})]}],
                zones:[{id:'safe',name:'Stop before the broken crossing',edge:'bridge-approach',from:35,to:340},
                    {id:'catch-yard',name:'Emergency gravel catch',edge:'catch',from:35,to:350,color:'#d9a168'}],
                tasks:[{id:'rescue',type:'rescue',zone:'safe',alternative:'catch-yard',cars:['R1','R2','R3'],text:'All three wagons stopped and secured before the river'}]
            },[350,500,750]),
        level('long-grade-6','Leaves on the Line',
            'Take the timber freight over the wooded saddle in steady rain. Build momentum on the approach, ease power through the leaf-covered cutting, and control the descent to the paper works.',
            'Amber wagons are sliding or spinning. Lower brake settings can grip better than full service on wet leaves. The approach curve limits the speed you can carry into the climb.',
            [2100,1150],{
                scenery:'woodland',weather:'rain',thermal:false,tractive:105000,
                nodes:{yard:[80,760,25],bend:[650,760,25],summit:[1170,470,29],out:[1580,560,25],works:[2000,740,25]},
                tracks:[{id:'approach',a:'yard',b:'bend',limit:8,adhesion:.12},
                    {id:'cutting',a:'bend',b:'summit',points:[[650,760,25],[800,660,26.2],[970,550,27.6],[1170,470,29]],limit:7,adhesion:.035,restrictions:[{from:0,to:.2,limit:6.5}]},
                    {id:'wet-descent',a:'summit',b:'out',points:[[1170,470,29],[1320,415,27.8],[1450,470,26.3],[1580,560,25]],limit:6,adhesion:.035,restrictions:[{from:.35,to:.7,limit:4.5}]},
                    {id:'works-road',a:'out',b:'works',limit:5,adhesion:.12}],
                switches:[],groups:[{cars:[loco('approach',260),...Array.from({length:8},(_,i)=>wagon('W'+(i+1),'approach',240.8-i*17.2,{mass:35000}))]}],
                zones:[{id:'works',name:'Paper works',edge:'works-road',from:40,to:410}],
                tasks:[{id:'timber',type:'park',zone:'works',cars:['engine',...Array.from({length:8},(_,i)=>'W'+(i+1))],text:'Timber freight secured inside the works'}]
            },[500,750,1100]),
        level('long-grade-7','One Bridge, Two Loads',
            'Shuttle two transformers across the temporary bridge. It carries one transformer, its support wagon and the locomotive. Assemble the freight on the far side with load 2 ahead of load 1.',
            'The locomotive starts between the loads. Push load 1 into the pocket, then bring load 2 to the assembly road. The empty engine can leave by the return loop. Keep each numbered support beside its transformer.',
            [1600,950],{
                scenery:'valley',thermal:false,
                river:[[680,0],[745,190],[720,470],[660,680],[720,950]],
                nodes:{west:[80,470,20],w:[650,470,20],e:[790,470,20],end:[1490,470,20],pocket:[1190,800,20]},
                tracks:[{id:'west-yard',a:'west',b:'w',limit:7},
                    {id:'bridge',a:'w',b:'e',limit:3,bridge:{name:'Temporary bridge',maxMass:205000,maxLoads:1}},
                    {id:'receiving',a:'e',b:'end',limit:6},
                    {id:'pocket',a:'e',b:'pocket',points:[[790,470,20],[940,680,20],[1190,800,20]],limit:5},
                    {id:'return',a:'end',b:'e',points:[[1490,470,20],[1470,290,20],[1100,250,20],[890,310,20],[790,470,20]],limit:5}],
                switches:[{node:'e',label:'Receiving points',stem:'bridge',branches:['receiving','pocket','return'],names:['Assembly road','Receiving pocket','Engine return loop']}],
                groups:[{cars:[wagon('T1','west-yard',350,{length:24,mass:110000,heavy:true}),wagon('E1','west-yard',328.8,{length:16,mass:10000}),loco('west-yard',309.6),wagon('T2','west-yard',286.4,{length:24,mass:110000,heavy:true}),wagon('E2','west-yard',265.2,{length:16,mass:10000})]}],
                zones:[{id:'final',name:'Assembly · 2 then 1 toward buffers',edge:'receiving',from:70,to:640},
                    {id:'pocket-zone',name:'Receiving pocket',edge:'pocket',from:60,to:420}],
                tasks:[{id:'transformers',type:'park',zone:'final',cars:['engine','T1','E1','T2','E2'],order:['T2','E2','T1','E1'],text:'Complete train secured; load 2 and support ahead of load 1'}]
            },[900,1350,1900]),
        level('long-grade-8','The Corners Are the Cargo',
            'Move the long industrial vessel into the export terminal. Its carrier wagons fit the rails; its ends swing far beyond them on curves.',
            'The translucent outline previews the vessel along your selected route. Red outlines mark a clearance collision. Choose both ends of the broad route before moving.',
            [2000,1100],{
                scenery:'yard',thermal:false,
                nodes:{start:[70,450,10],fork:[560,450,10],join:[1260,450,10],end:[1900,450,10]},
                tracks:[{id:'arrival',a:'start',b:'fork',limit:7},
                    {id:'tight',a:'fork',b:'join',points:[[560,450,10],[680,320,10],[740,470,10],[900,560,10],[1060,330,10],[1260,450,10]],limit:4},
                    {id:'broad',a:'fork',b:'join',points:[[560,450,10],[650,740,10],[910,850,10],[1170,740,10],[1260,450,10]],limit:5},
                    {id:'terminal',a:'join',b:'end',limit:4}],
                switches:[{node:'fork',label:'Terminal west',stem:'arrival',branches:['tight','broad'],names:['Platform road','Broad freight road']},
                    {node:'join',label:'Terminal east',stem:'terminal',branches:['tight','broad'],names:['Platform road','Broad freight road']}],
                groups:[{cars:[loco('arrival',310),wagon('C1','arrival',278.8,{length:40,mass:65000}),wagon('C2','arrival',237.6,{length:40,mass:65000})]}],
                cargo:{cars:['C1','C2'],overhang:28,width:11},
                obstacles:[{name:'Loading platform',x:689,y:328,w:23,h:26},{name:'Signal cabin',x:1070,y:348,w:24,h:22}],
                zones:[{id:'terminal',name:'Export terminal',edge:'terminal',from:60,to:530}],
                tasks:[{id:'vessel',type:'park',zone:'terminal',cars:['engine','C1','C2'],text:'Vessel and carriers secured in the terminal'}]
            },[500,750,1100])
    ];
    if(typeof module!=='undefined'&&module.exports)module.exports=levels;
    root.RailLevels=levels;
})(typeof globalThis!=='undefined'?globalThis:this);
