// @ts-check
(function (/** @type {typeof globalThis} */ root) {
    'use strict';
    /** @param {string} id @param {string} edge @param {number} s
     * @param {Partial<import('./rail-level-types.js').Vehicle>} [extra]
     * @returns {import('./rail-level-types.js').Vehicle} */
    const wagon=(id,edge,s,extra={})=>({id,edge,s,length:16,mass:42000,...extra});
    /** @param {string} edge @param {number} s */
    const loco=(edge,s)=>wagon('engine',edge,s,{length:20,mass:80000,powered:true,name:'No. 17'});
    /** @param {string} id @param {string} name @param {string} brief @param {string} tip
     * @param {[number,number]} world @param {import('./rail-level-types.js').RailConfig} rail
     * @param {[number,number,number]} pace */
    const level=(id,name,brief,tip,world,rail,pace)=>({id,name,brief,tip,world,rail,pace,rulesRevision:3,
        kind:'Freight railway',start:[100,100,0],berth:{x:100,y:100,a:0,l:50,w:20,angle:10,speed:.2},
        spec:{name:'No. 17',length:20,beam:4,mass:80000}});
    const levels=[
        level('long-grade-1','The Last Wagon Counts',
            'Stop at the receiving board using the locomotive brake. Collect the two waiting wagons, then reverse clear of the junction and put the complete train in Quarry Siding.',
            'Couple below 2 km/h. Release the waiting wagons’ handbrakes after coupling. The junction lamp stays red until the last wagon clears.',
            [1100,650],{
                thermal:false,scenery:'quarry',
                nodes:{q:[90,465,18],j:[460,420,17],r:[990,470,17],s:[770,130,20]},
                tracks:[
                    {id:'approach',a:'q',b:'j',points:[[90,465,18],[240,485,18],[370,445,17],[460,420,17]],limit:10},
                    {id:'receiving',a:'j',b:'r',points:[[460,420,17],[650,380,17],[820,400,17],[990,470,17]],limit:7},
                    {id:'siding',a:'j',b:'s',points:[[460,420,17],[530,300,18],[650,200,19],[770,130,20]],limit:6}
                ],
                switches:[{node:'j',label:'Quarry Junction',stem:'approach',branches:['receiving','siding'],names:['Receiving yard','Quarry Siding']}],
                groups:[{cars:[loco('approach',230),wagon('Q1','approach',210.8),wagon('Q2','approach',193.6)]},
                    {secured:true,cars:[wagon('R1','receiving',201.2),wagon('R2','receiving',184)]}],
                zones:[{id:'board',name:'Receiving board',edge:'receiving',from:95,to:145,color:'#e0bd6c'},
                    {id:'final',name:'Quarry Siding',edge:'siding',from:65,to:290,color:'#82b99b'}],
                tasks:[{id:'first-stop',type:'stop',zone:'board',independent:true,text:'Stop at the receiving board'},
                    {id:'collect',type:'coupled',cars:['R1','R2'],after:'first-stop',text:'Collect both waiting wagons'},
                    {id:'park',type:'park',zone:'final',cars:['engine','Q1','Q2','R1','R2'],after:'collect',text:'Whole train in Quarry Siding, handbrakes set'}]
            },[300,480,750]),
        level('long-grade-2','Head at the Wrong End',
            'Push the blue wagons into the mill siding and leave them secured. The orange wagons belong in the foundry siding at the other end. Run the engine around them before the second push.',
            'Select a wagon to set its cut’s handbrakes. Uncouple using a link in the train strip. The short loop has room for the engine, not the whole freight.',
            [1050,680],{
                thermal:false,scenery:'yard',
                nodes:{west:[70,350,12],a:[245,350,12],w:[400,350,12],e:[550,350,12],b:[760,350,12],east:[990,350,12],mill:[150,610,15],foundry:[900,90,15]},
                tracks:[
                    {id:'west-head',a:'west',b:'a',limit:6},
                    {id:'west-neck',a:'a',b:'w',limit:6},
                    {id:'main',a:'w',b:'e',points:[[400,350,12],[380,455,11],[470,520,10.4],[570,455,11],[550,350,12]],limit:6},
                    {id:'loop',a:'w',b:'e',points:[[400,350,12],[440,335,12],[510,335,12],[550,350,12]],limit:5},
                    {id:'east-neck',a:'e',b:'b',limit:6},
                    {id:'east-head',a:'b',b:'east',limit:6},
                    {id:'mill',a:'a',b:'mill',points:[[245,350,12],[210,460,13],[150,610,15]],limit:4},
                    {id:'foundry',a:'b',b:'foundry',points:[[760,350,12],[805,210,13],[900,90,15]],limit:4}
                ],
                switches:[
                    {node:'a',label:'Mill points',stem:'west-neck',branches:['west-head','mill'],names:['West headshunt','Mill siding']},
                    {node:'w',label:'West loop',stem:'west-neck',branches:['main','loop'],names:['Station road','Run-around']},
                    {node:'e',label:'East loop',stem:'east-neck',branches:['main','loop'],names:['Station road','Run-around']},
                    {node:'b',label:'Foundry points',stem:'east-neck',branches:['east-head','foundry'],names:['East headshunt','Foundry siding']}
                ],
                groups:[{cars:[loco('main',320),...['F1','F2','F3','F4','M1','M2'].map((id,i)=>wagon(id,'main',296.8-i*25.2,{length:24,mass:35000,destination:id[0]==='M'?'mill':'foundry'}))]}],
                zones:[{id:'mill-yard',name:'Mill · blue wagons',edge:'mill',from:50,to:230,color:'#79b9cd'},
                    {id:'foundry-yard',name:'Foundry · orange wagons',edge:'foundry',from:55,to:265,color:'#d89763'}],
                tasks:[{id:'mill-load',type:'delivery',zone:'mill-yard',cars:['M1','M2'],text:'Blue wagons secured at the mill; engine detached'},
                    {id:'foundry-load',type:'delivery',zone:'foundry-yard',cars:['F1','F2','F3','F4'],text:'Orange wagons secured at the foundry; engine detached'}]
            },[650,1000,1500]),
        level('long-grade-3','Stone Runs Downhill',
            'Bring the stone freight down to the valley works. The direct descent has tight bends; the eastern branch is longer and gentler. Both lead to a cooling loop above the works.',
            'Choose your route at both ends of each branch. Watch the tail’s grade and brake temperature. A cool train with room to stop is worth the extra distance.',
            [1750,1250],{
                thermal:true,scenery:'valley',
                nodes:{quarry:[100,140,62],summit:[500,140,60],join:[950,790,27],cool:[1090,905,25],out:[1270,1020,23],works:[1620,1130,22]},
                tracks:[
                    {id:'plateau',a:'quarry',b:'summit',limit:15},
                    {id:'steep',a:'summit',b:'join',points:[[500,140,60],[640,255,57],[715,390,48],[665,535,41],[770,665,33],[950,790,27]],limit:13,restrictions:[{from:.24,to:.63,limit:5.5}]},
                    {id:'gentle',a:'summit',b:'join',points:[[500,140,60],[970,90,54],[1450,240,46],[1460,600,36],[1230,735,30],[950,790,27]],limit:10},
                    {id:'valley',a:'join',b:'cool',limit:8},
                    {id:'direct',a:'cool',b:'out',limit:7},
                    {id:'cooling',a:'cool',b:'out',points:[[1090,905,25],[920,1010,24.5],[700,985,24],[660,1140,23.8],[980,1190,23.5],[1270,1020,23]],limit:7},
                    {id:'works-road',a:'out',b:'works',limit:5}
                ],
                switches:[{node:'summit',label:'Summit',stem:'plateau',branches:['steep','gentle'],names:['Direct descent','Eastern branch']},
                    {node:'join',label:'Valley Junction',stem:'valley',branches:['steep','gentle'],names:['Direct descent','Eastern branch']},
                    {node:'cool',label:'Loop entrance',stem:'valley',branches:['direct','cooling'],names:['Works approach','Cooling loop']},
                    {node:'out',label:'Works Junction',stem:'works-road',branches:['direct','cooling'],names:['Works approach','Cooling loop']}],
                groups:[{cars:[loco('plateau',270),...Array.from({length:10},(_,i)=>wagon('S'+(i+1),'plateau',250.8-i*17.2,{mass:65000}))]}],
                zones:[{id:'works-yard',name:'Valley works',edge:'works-road',from:35,to:345,color:'#82b99b'}],
                tasks:[{id:'stone',type:'park',zone:'works-yard',cars:['engine',...Array.from({length:10},(_,i)=>'S'+(i+1))],text:'All stone wagons inside the works, handbrakes set'}]
            },[450,650,950]),
        level('long-grade-4','Meet at Rook’s Hollow',
            'An opposing passenger service is due through the valley. Meet it at Rook’s Hollow, then bring the complete freight into East Yard.',
            'Rook’s loop fits the freight; the short refuge does not. Clear both points, set them back to Main line, then press H to signal the passenger’s departure. It waits at red signals if its route is blocked.',
            [2200,850],{
                scenery:'valley',thermal:false,
                nodes:{west:[80,450,20],exit:[65,110,20],a:[570,450,20],b:[1090,450,20],c:[1460,450,18],d:[1590,450,18],east:[2130,450,18]},
                tracks:[{id:'west-road',a:'west',b:'a',limit:10},
                    {id:'west-tunnel',a:'west',b:'exit',points:[[80,450,20],[35,350,20],[45,240,20],[65,110,20]],limit:8,tunnel:{from:180,name:'Rook tunnel'}},
                    {id:'hollow-main',a:'a',b:'b',limit:10},
                    {id:'hollow-loop',a:'a',b:'b',points:[[570,450,20],[680,590,20],[960,590,20],[1090,450,20]],limit:6},
                    {id:'valley-road',a:'b',b:'c',limit:10},
                    {id:'refuge-main',a:'c',b:'d',limit:10},
                    {id:'refuge-loop',a:'c',b:'d',points:[[1460,450,18],[1500,370,18],[1560,370,18],[1590,450,18]],limit:5},
                    {id:'east-road',a:'d',b:'east',limit:8}],
                switches:[{node:'a',label:'Rook west',stem:'west-road',branches:['hollow-main','hollow-loop'],names:['Main line','Rook’s loop']},
                    {node:'b',label:'Rook east',stem:'valley-road',branches:['hollow-main','hollow-loop'],names:['Main line','Rook’s loop']},
                    {node:'c',label:'Refuge west',stem:'valley-road',branches:['refuge-main','refuge-loop'],names:['Main line','Short refuge']},
                    {node:'d',label:'Refuge east',stem:'east-road',branches:['refuge-main','refuge-loop'],names:['Main line','Short refuge']}],
                groups:[{cars:[loco('west-road',365),...Array.from({length:12},(_,i)=>wagon('H'+(i+1),'west-road',339.8-i*29.2,{length:28,mass:32000}))]}],
                traffic:[{id:'passenger',name:'Valley passenger',speed:7,route:[['east-road',-1],['refuge-main',-1],['valley-road',-1],['hollow-main',-1],['west-road',-1],['west-tunnel',1]],head:125,length:110}],
                zones:[{id:'hollow',name:'Rook’s Hollow · full freight',edge:'hollow-loop',from:30,to:590},
                    {id:'refuge',name:'Short refuge · engine + cut',edge:'refuge-loop',from:22,to:170},
                    {id:'east-yard',name:'East Yard',edge:'east-road',from:35,to:505}],
                tasks:[{id:'meet',type:'traffic',traffic:'passenger',text:'Let the passenger clear the valley'},
                    {id:'freight',type:'park',after:'meet',zone:'east-yard',cars:['engine',...Array.from({length:12},(_,i)=>'H'+(i+1))],text:'Whole freight in East Yard, handbrakes set'}]
            },[650,900,1300]),
        level('long-grade-5','Three Wagons Going Somewhere',
            'Three stone wagons are running toward a broken river crossing. Catch them from the service line, couple below 2 km/h relative speed, and stop in the bridge approach.',
            'The early connection gives more stopping room. The longer service branch reaches a second interception on a gentler grade. The gravel catch siding saves the wagons, but the finish will be rough.',
            [2300,1000],{
                scenery:'valley',thermal:false,
                river:[[2120,0],[2070,190],[2160,400],[2140,650],[2220,1000]],
                nodes:{top:[80,290,27],early:[650,400,24],late:[1390,400,23],fork:[1740,400,22.5],broken:[2200,400,22.5],service:[270,680,24],catch:[1910,780,24]},
                tracks:[{id:'runaway-road',a:'top',b:'early',limit:18},
                    {id:'main-descent',a:'early',b:'late',points:[[650,400,24],[920,390,21.5],[1160,400,22.5],[1390,400,23]],limit:16},
                    {id:'service',a:'service',b:'early',limit:12},
                    {id:'service-long',a:'service',b:'late',points:[[270,680,24],[800,790,23],[1260,650,23],[1390,400,23]],limit:12},
                    {id:'bridge-road',a:'late',b:'fork',limit:12},
                    {id:'bridge-approach',a:'fork',b:'broken',limit:10,closedFrom:410},
                    {id:'catch',a:'fork',b:'catch',limit:14,catchFrom:120}],
                switches:[{node:'service',label:'Service fork',stem:'service',branches:['service-long'],names:['Later interception']},
                    {node:'early',label:'Early interception',stem:'main-descent',branches:['runaway-road','service'],names:['Quarry line','Service line']},
                    {node:'late',label:'Late interception',stem:'bridge-road',branches:['main-descent','service-long'],names:['Main descent','Long service line']},
                    {node:'fork',label:'Bridge points',stem:'bridge-road',branches:['bridge-approach','catch'],names:['Bridge approach','Emergency catch']}],
                groups:[{cars:[loco('service',180)]},{brake:0,speed:2.8,cars:[wagon('R1','runaway-road',300,{mass:65000}),wagon('R2','runaway-road',282.8,{mass:65000}),wagon('R3','runaway-road',265.6,{mass:65000})]}],
                zones:[{id:'safe',name:'Stop before the broken crossing',edge:'bridge-approach',from:35,to:340},
                    {id:'catch-yard',name:'Emergency gravel catch',edge:'catch',from:35,to:350,color:'#d9a168'}],
                tasks:[{id:'catch-wagons',type:'coupled',milestone:true,cars:['R1','R2','R3'],text:'Couple to the three runaway wagons'},
                    {id:'rescue',type:'rescue',zone:'safe',alternative:'catch-yard',cars:['R1','R2','R3'],text:'Wagons secured before the river (or in the catch siding)'}]
            },[350,500,750]),
        level('long-grade-6','Leaves on the Line',
            'Take the timber freight over the wooded saddle in steady rain. Build momentum on the approach, ease power through the leaf-covered cutting, and control the descent to the paper works.',
            'Amber wagons are sliding or spinning. Lower brake settings can grip better than full service on wet leaves. The approach curve limits the speed you can carry into the climb.',
            [2100,1150],{
                scenery:'woodland',weather:'rain',thermal:false,tractive:105000,
                nodes:{yard:[80,760,25],bend:[650,760,25],summit:[1170,470,29],out:[1580,560,25],works:[2000,740,25]},
                tracks:[{id:'approach',a:'yard',b:'bend',limit:8,adhesion:.12},
                    {id:'cutting',a:'bend',b:'summit',points:[[650,760,25],[800,660,26.2],[970,550,27.6],[1170,470,29]],limit:7,adhesion:.035,restrictions:[{from:0,to:.2,limit:6.5}]},
                    {id:'wet-descent',a:'summit',b:'out',points:[[1170,470,29],[1320,415,27.8],[1450,470,26.3],[1580,560,25]],limit:6,adhesion:.035,restrictions:[{from:.35,to:.7,limit:4.5}]},
                    {id:'works-road',a:'out',b:'works',limit:5,adhesion:.12}],
                switches:[],groups:[{cars:[loco('approach',260),...Array.from({length:8},(_,i)=>wagon('W'+(i+1),'approach',240.8-i*17.2,{mass:35000}))]}],
                zones:[{id:'works',name:'Paper works',edge:'works-road',from:40,to:410}],
                tasks:[{id:'timber',type:'park',zone:'works',cars:['engine',...Array.from({length:8},(_,i)=>'W'+(i+1))],text:'Timber freight secured inside the works'}]
            },[500,750,1100]),
        level('long-grade-7','One Bridge, Two Loads',
            'Shuttle two transformers across the temporary bridge. It carries one transformer, its support wagon and the locomotive. Assemble the freight on the far side with load 2 ahead of load 1.',
            'The locomotive starts between the loads. Push load 1 into the pocket, then bring load 2 to the assembly road. The empty engine can leave by the return loop. Keep each numbered support beside its transformer.',
            [1600,950],{
                scenery:'valley',thermal:false,
                river:[[680,0],[745,190],[720,470],[660,680],[720,950]],
                nodes:{west:[80,470,20],w:[650,470,20],e:[790,470,20],end:[1490,470,20],pocket:[1190,800,20]},
                tracks:[{id:'west-yard',a:'west',b:'w',limit:7},
                    {id:'bridge',a:'w',b:'e',limit:3,bridge:{name:'Temporary bridge',maxMass:205000,maxLoads:1,pairs:[['T1','E1'],['T2','E2']]}},
                    {id:'receiving',a:'e',b:'end',limit:6},
                    {id:'pocket',a:'e',b:'pocket',points:[[790,470,20],[940,680,20],[1190,800,20]],limit:5},
                    {id:'return',a:'end',b:'e',points:[[1490,470,20],[1470,290,20],[1100,250,20],[890,310,20],[790,470,20]],limit:5}],
                switches:[{node:'e',label:'Receiving points',stem:'bridge',branches:['receiving','pocket','return'],names:['Assembly road','Receiving pocket','Engine return loop']}],
                groups:[{cars:[wagon('T1','west-yard',350,{length:24,mass:110000,heavy:true}),wagon('E1','west-yard',328.8,{length:16,mass:10000}),loco('west-yard',309.6),wagon('T2','west-yard',286.4,{length:24,mass:110000,heavy:true}),wagon('E2','west-yard',265.2,{length:16,mass:10000})]}],
                zones:[{id:'final',name:'Assembly · 2 then 1 toward buffers',edge:'receiving',from:70,to:640},
                    {id:'pocket-zone',name:'Receiving pocket',edge:'pocket',from:60,to:420},
                    {id:'waiting-load',name:'West holding track',edge:'west-yard',from:80,to:500}],
                tasks:[
                    {id:'leave-load-2',type:'delivery',milestone:true,zone:'waiting-load',cars:['T2','E2'],text:'1 · Detach and secure load 2 + support before crossing'},
                    {id:'pocket-load-1',type:'delivery',milestone:true,zone:'pocket-zone',cars:['T1','E1'],text:'2 · Leave load 1 + support secured in the pocket'},
                    {id:'assembly-load-2',type:'delivery',milestone:true,zone:'final',cars:['T2','E2'],text:'3 · Leave load 2 + support secured on the assembly road'},
                    {id:'rejoin-loads',type:'coupled',milestone:true,after:'assembly-load-2',cars:['T1','E1','T2','E2'],text:'4 · Use the return loop; collect load 1 and rejoin the freight'},
                    {id:'transformers',type:'park',zone:'final',cars:['engine','T1','E1','T2','E2'],order:['T2','E2','T1','E1'],text:'5 · Park and secure all wagons, load 2 ahead; clear the points'}]
            },[900,1350,1900]),
        level('long-grade-8','The Corners Are the Cargo',
            'The broad road is clear for ordinary wagons, but this vessel’s ends sweep across the neighbouring siding. Leave the carriers secured, use the locomotive to move the parked flats out of that sweep, then return for the vessel.',
            'Shunt P1 and P2 into the marked refuge, or find another place outside the swept outline. Rejoin the carriers, take the broad road, and reverse from the headshunt into the export berth. Preview the load’s corners before committing.',
            [2000,1100],{
                scenery:'yard',thermal:false,
                nodes:{start:[70,450,10],fork:[560,450,10],join:[1260,450,10],head:[1780,150,10],end:[1850,910,10],refuge:[1120,650,10]},
                tracks:[{id:'arrival',a:'start',b:'fork',limit:7},
                    {id:'tight',a:'fork',b:'join',points:[[560,450,10],[680,320,10],[740,470,10],[900,560,10],[1060,330,10],[1260,450,10]],limit:4},
                    {id:'broad',a:'fork',b:'join',points:[[560,450,10],[650,740,10],[910,850,10],[1170,740,10],[1260,450,10]],limit:5},
                    {id:'clearance-road',a:'fork',b:'refuge',points:[[560,450,10],[565,690,10],[670,780,10],[1040,780,10],[1120,650,10]],limit:4},
                    {id:'headshunt',a:'join',b:'head',limit:4},
                    {id:'terminal',a:'join',b:'end',points:[[1260,450,10],[1510,510,10],[1750,690,10],[1850,910,10]],limit:4}],
                switches:[{node:'fork',label:'Terminal west',stem:'arrival',branches:['tight','broad','clearance-road'],names:['Platform road','Broad freight road','Clearance siding']},
                    {node:'join',label:'Export points',stem:'headshunt',branches:['tight','broad','terminal'],names:['Platform road','Broad freight road','Export spur']}],
                groups:[{cars:[loco('arrival',310),wagon('C1','arrival',278.8,{length:40,mass:65000}),wagon('C2','arrival',237.6,{length:40,mass:65000})]},
                    {secured:true,cars:[wagon('P1','clearance-road',380,{mass:12000}),wagon('P2','clearance-road',362.8,{mass:12000})]}],
                cargo:{cars:['C1','C2'],overhang:40,width:14,clearanceWagons:['P1','P2']},
                obstacles:[{name:'Loading platform',x:689,y:328,w:23,h:26},{name:'Signal cabin',x:1070,y:348,w:24,h:22}],
                zones:[{id:'vessel-wait',name:'Carrier holding track',edge:'arrival',from:180,to:320},
                    {id:'refuge',name:'Flat wagon refuge',edge:'clearance-road',from:620,to:800},
                    {id:'turn',name:'Whole load beyond this mark · stop and reverse',edge:'headshunt',from:140,to:450},
                    {id:'terminal',name:'Export berth',edge:'terminal',from:340,to:670}],
                tasks:[{id:'leave-vessel',type:'delivery',milestone:true,zone:'vessel-wait',cars:['C1','C2'],text:'Leave the carriers secured; free the locomotive'},
                    {id:'collect-flats',type:'coupled',milestone:true,cars:['P1','P2'],text:'Couple to the parked flats on the clearance siding'},
                    {id:'clear-flats',type:'delivery',milestone:true,zone:'refuge',cars:['P1','P2'],text:'Shunt the parked flats clear of the vessel’s sweep'},
                    {id:'rejoin-vessel',type:'coupled',milestone:true,after:'collect-flats',cars:['C1','C2'],text:'Return for the vessel and rejoin the carriers'},
                    {id:'clear-load',type:'position',zone:'turn',cars:['engine','C1','C2'],text:'Stop with the whole load inside the headshunt mark'},
                    {id:'vessel',type:'park',after:'clear-load',zone:'terminal',cars:['engine','C1','C2'],text:'Reverse into the export berth and secure the carriers'}]
            },[700,1000,1400]),
        level('long-grade-9','A Push from Behind',
            'Reverse the ore train gently onto the waiting helper, then take both engines over the saddle. Leave the helper secured in Summit Yard and deliver the freight to the valley exchange.',
            'Stop close to the helper and couple with F, release its handbrake, then reverse for the climb. E / Q raises / lowers rear assistance. Share the climb; ease front power at the crest, then the rear as the tail comes over.',
            [2600,1200],{
                scenery:'valley',thermal:false,helper:{tractive:190000,workingPull:130000,pullGrace:16,compressionGrace:3},couplerLimit:300000,compressionLimit:140000,
                nodes:{start:[80,700,20],foot:[680,700,20],crest:[1380,410,40],yard:[1910,490,38],end:[2470,930,28]},
                tracks:[{id:'approach',a:'start',b:'foot',points:[[80,700,20],[280,740,20],[490,735,20],[680,700,20]],limit:8},
                    {id:'climb',a:'foot',b:'crest',points:[[680,700,20],[900,580,26],[1140,470,34],[1380,410,40]],limit:8},
                    {id:'summit-yard',a:'crest',b:'yard',points:[[1380,410,40],[1520,400,38],[1710,450,38],[1910,490,38]],limit:6},
                    {id:'exchange',a:'yard',b:'end',points:[[1910,490,38],[2100,680,34],[2290,850,29],[2470,930,28]],limit:6}],switches:[],
                groups:[{cars:[loco('approach',360),...Array.from({length:8},(_,i)=>wagon('O'+(i+1),'approach',336.8-i*25.2,{length:24,mass:65000}))]},
                    {secured:true,cars:[{...loco('approach',60),id:'helper',helper:true,name:'No. 42'}]}],
                zones:[{id:'helper-yard',name:'Helper berth',edge:'summit-yard',from:110,to:240},
                    {id:'exchange',name:'Valley exchange',edge:'exchange',from:350,to:690}],
                tasks:[{id:'assist',type:'coupled',cars:['helper'],text:'Couple the rear helper'},
                    {id:'retire',type:'retire',after:'assist',zone:'helper-yard',cars:['helper'],text:'Helper detached and secured in Summit Yard'},
                    {id:'ore',type:'park',after:'retire',exclude:['helper'],zone:'exchange',cars:['engine',...Array.from({length:8},(_,i)=>'O'+(i+1))],text:'Complete ore freight secured at the exchange'}]
            },[900,1300,1900]),
        level('long-grade-10','The Railway Ends Here',
            'Put one pair of freight wagons on each ferry track. Use the reach wagon to keep the engine ashore. Leave both pairs secured aboard and park the engine with its reach wagon on the quay.',
            'The first pair nearly uses the ferry’s balance reserve. Use the quay loop to get behind the second pair, then push it onto the other deck track. Watch the ramp and port–starboard load difference.',
            [1500,950],{
                scenery:'port',thermal:false,ferry:{decks:['port','starboard'],start:80,maxDifference:65000},
                nodes:{west:[90,470,5],fork:[740,470,5],p:[1230,420,5],s:[1230,550,5]},
                tracks:[{id:'quay',a:'west',b:'fork',limit:5},
                    {id:'port',a:'fork',b:'p',points:[[740,470,5],[825,420,5],[1000,420,5],[1230,420,5]],limit:2},
                    {id:'starboard',a:'fork',b:'s',points:[[740,470,5],[825,550,5],[1000,550,5],[1230,550,5]],limit:2},
                    {id:'quay-loop',a:'fork',b:'west',points:[[740,470,5],[620,700,5],[270,720,5],[90,470,5]],limit:4}],
                switches:[{node:'fork',label:'Ferry points',stem:'quay',branches:['port','starboard','quay-loop'],names:['Port deck','Starboard deck','Quay loop']}],
                groups:[{cars:[wagon('A1','quay',379.6,{length:24,mass:25000}),wagon('A2','quay',354.4,{length:24,mass:25000}),wagon('reach','quay',325.2,{length:32,mass:12000}),loco('quay',298),wagon('B1','quay',274.8,{length:24,mass:25000}),wagon('B2','quay',249.6,{length:24,mass:25000})]}],
                zones:[{id:'port-load',name:'Port deck · pair A',edge:'port',from:90,to:230},
                    {id:'starboard-load',name:'Starboard deck · pair B',edge:'starboard',from:90,to:230},
                    {id:'quay-park',name:'Engine + reach wagon',edge:'quay',from:390,to:580}],
                tasks:[{id:'port',type:'ferry',zone:'port-load',cars:['A1','A2'],text:'Pair A secured on the port deck'},
                    {id:'starboard',type:'ferry',zone:'starboard-load',cars:['B1','B2'],text:'Pair B secured on the starboard deck'},
                    {id:'ashore',type:'park',zone:'quay-park',cars:['engine','reach'],exclude:['A1','A2','B1','B2'],text:'Locomotive and reach wagon secured ashore'}]
            },[1000,1500,2100]),
        level('long-grade-11','The Last Working Line',
            'Collect the lowland wagons, the quarry cut and the maintenance crew before floodwater cuts off the branch. Bring everyone to the upland junction with every wagon secured.',
            'Low Crossing closes first; Quarry Neck floods later. Collect the lowland cut before entering the dead-end quarry spur. Stop at the crew platform for five seconds. Closed track stays closed, but every open route remains usable.',
            [2200,1250],{
                scenery:'valley',weather:'rain',thermal:false,
                river:[[620,0],[690,300],[610,700],[660,1000],[610,1250]],
                nodes:{low:[110,940,8],west:[800,850,12],j:[1320,620,18],quarry:[1430,110,24],up:[2070,510,32]},
                tracks:[{id:'low-road',a:'low',b:'west',points:[[110,940,8],[400,1000,8],[650,930,9],[800,850,12]],limit:7},
                    {id:'branch',a:'west',b:'j',limit:7},
                    {id:'quarry-spur',a:'j',b:'quarry',points:[[1320,620,18],[1490,420,19],[1510,220,22],[1430,110,24]],limit:5},
                    {id:'upland',a:'j',b:'up',points:[[1320,620,18],[1620,530,26],[1840,510,30],[2070,510,32]],limit:7}],
                switches:[{node:'j',label:'Upland junction',stem:'branch',branches:['quarry-spur','upland'],names:['Quarry spur','Upland yard']}],
                floods:[{name:'Low Crossing',edge:'low-road',from:470,to:660,at:1100},
                    {name:'Quarry Neck',edge:'quarry-spur',from:45,to:180,at:2200}],
                groups:[{cars:[loco('branch',240),wagon('V1','branch',220.8,{mass:30000})]},
                    {secured:true,cars:[wagon('L1','low-road',300,{mass:50000}),wagon('L2','low-road',282.8,{mass:50000})]},
                    {secured:true,cars:[wagon('Q1','quarry-spur',300,{mass:45000}),wagon('Q2','quarry-spur',282.8,{mass:45000})]}],
                zones:[{id:'crew-platform',name:'Maintenance crew · 5 s stop',edge:'quarry-spur',from:380,to:460},
                    {id:'upland',name:'Upland refuge',edge:'upland',from:410,to:710}],
                tasks:[{id:'lowland',type:'coupled',cars:['L1','L2'],text:'Collect the lowland cut before Low Crossing floods'},
                    {id:'quarry',type:'coupled',cars:['Q1','Q2'],text:'Collect both quarry wagons'},
                    {id:'crew',type:'crew',zone:'crew-platform',dwell:5,text:'Stop at the platform and board the maintenance crew'},
                    {id:'refuge',type:'park',after:'crew',zone:'upland',cars:['engine','V1','L1','L2','Q1','Q2'],text:'Everyone at the upland refuge; all handbrakes set'}]
            },[1100,1600,2100]),
        level('long-grade-12','The Long Grade',
            'Bring the winter-supply freight from the plateau to the coastal terminal. Use the rear helper across the summit, leave it secured in Summit Yard, then manage the long descent and meet the coastal passenger at Lantern Viaduct.',
            'Ease each engine as its end crests. Fit the whole freight in Lantern loop, set both ends to Main viaduct and Summit Junction to Ridge tunnel, then signal the passenger with H. Keep cool brakes for the terminal.',
            [3800,2000],{
                scenery:'valley',weather:'snow',thermal:true,helper:{tractive:190000},couplerLimit:260000,compressionLimit:135000,
                nodes:{start:[80,220,40],foot:[620,220,40],crest:[1330,360,65],yard:[1940,500,63],tunnel:[2510,240,63],a:[2210,1120,31],b:[2750,1240,28],end:[3640,1770,13]},
                tracks:[{id:'plateau',a:'start',b:'foot',limit:9},
                    {id:'summit',a:'foot',b:'crest',points:[[620,220,40],[850,210,49],[1090,275,58],[1330,360,65]],limit:8},
                    {id:'summit-yard',a:'crest',b:'yard',points:[[1330,360,65],[1490,420,63],[1720,460,63],[1940,500,63]],limit:6},
                    {id:'descent',a:'yard',b:'a',points:[[1940,500,63],[2150,650,55],[2020,850,42],[2210,1120,31]],limit:10,restrictions:[{from:.3,to:.7,limit:5}]},
                    {id:'ridge-tunnel',a:'yard',b:'tunnel',points:[[1940,500,63],[2160,415,63],[2350,325,63],[2510,240,63]],limit:8,tunnel:{from:350,name:'Ridge tunnel'}},
                    {id:'viaduct-main',a:'a',b:'b',limit:8},
                    {id:'lantern-loop',a:'a',b:'b',points:[[2210,1120,31],[2290,1320,30],[2580,1440,29],[2750,1240,28]],limit:5},
                    {id:'coastal-road',a:'b',b:'end',points:[[2750,1240,28],[3030,1330,24],[3170,1520,18],[3430,1740,13],[3640,1770,13]],limit:7,restrictions:[{from:.45,to:.8,limit:4}]}],
                switches:[{node:'yard',label:'Summit Junction',stem:'descent',branches:['summit-yard','ridge-tunnel'],names:['Summit Yard','Ridge tunnel']},
                    {node:'a',label:'Lantern west',stem:'descent',branches:['viaduct-main','lantern-loop'],names:['Main viaduct','Long passing loop']},
                    {node:'b',label:'Lantern east',stem:'coastal-road',branches:['viaduct-main','lantern-loop'],names:['Main viaduct','Long passing loop']}],
                groups:[{cars:[loco('plateau',390),...Array.from({length:10},(_,i)=>wagon('S'+(i+1),'plateau',366.8-i*25.2,{length:24,mass:60000}))]},
                    {secured:true,cars:[{...loco('plateau',116.8),id:'helper',helper:true,name:'No. 42'}]}],
                traffic:[{id:'coastal',name:'Coastal passenger',speed:6,route:[['coastal-road',-1],['viaduct-main',-1],['descent',-1],['ridge-tunnel',1]],head:125,length:110}],
                zones:[{id:'helper-yard',name:'Summit helper berth',edge:'summit-yard',from:100,to:240},
                    {id:'passing',name:'Lantern loop · whole freight',edge:'lantern-loop',from:35,to:700},
                    {id:'terminal',name:'Coastal terminal',edge:'coastal-road',from:650,to:1030}],
                tasks:[{id:'assist',type:'coupled',cars:['helper'],text:'Couple the helper for the summit'},
                    {id:'retire',type:'retire',after:'assist',zone:'helper-yard',cars:['helper'],text:'Leave the helper secured in Summit Yard'},
                    {id:'meet',type:'traffic',traffic:'coastal',text:'Let the coastal passenger clear Lantern Viaduct'},
                    {id:'winter',type:'park',after:'retire',exclude:['helper'],zone:'terminal',cars:['engine',...Array.from({length:10},(_,i)=>'S'+(i+1))],text:'Every supply wagon delivered; points clear; handbrakes set'}]
            },[2300,2900,3800])
    ];
    if(typeof module!=='undefined'&&module.exports)module.exports=levels;
    root.RailLevels=levels;
})(globalThis);
