/* Generated by tools/sync-replays.cjs from the checked-in control recordings. */
(function (root) {
    'use strict';
    const runs = [
    {
        "level": "crosscurrent",
        "events": [
            {
                "time": 0,
                "throttle": 4,
                "thruster": -1
            },
            {
                "time": 5.212383930767489,
                "thruster": 0
            },
            {
                "time": 50.682461793005615,
                "throttle": -3
            },
            {
                "time": 60.40500102776396,
                "thruster": 1
            },
            {
                "time": 68.67199376076813,
                "thruster": 0
            },
            {
                "time": 70.37714572310645,
                "throttle": 0
            }
        ],
        "duration": 80.61477385974001,
        "expectedTime": 78.64166666666667,
        "description": "Fixed-time controls only; no repositioning or objective shortcuts.",
        "source": "tests/exposed-crosscurrent-controls.json"
    },
    {
        "level": "first-crossing",
        "description": "Fixed-time player inputs only. No repositioning, altered physics or objective-state shortcuts.",
        "events": [
            {
                "time": 8,
                "throttle": 4
            },
            {
                "time": 76.6,
                "throttle": -3
            },
            {
                "time": 108.45,
                "throttle": 0
            }
        ],
        "duration": 129,
        "expectedTime": 123.95,
        "source": "tests/fixtures/first-crossing-controls.json"
    },
    {
        "level": "bigger-boat",
        "description": "Fixed-time player inputs only. No repositioning, altered physics or objective-state shortcuts.",
        "events": [
            {
                "time": 0,
                "line": true
            },
            {
                "time": 0,
                "throttle": 4
            },
            {
                "time": 35,
                "line": true
            },
            {
                "time": 63.45,
                "throttle": -3
            },
            {
                "time": 77,
                "throttle": 0
            }
        ],
        "duration": 193,
        "expectedTime": 187.9,
        "source": "tests/fixtures/bigger-boat-controls.json"
    }
];
    for (const run of runs) {
        run.events.forEach(Object.freeze);
        Object.freeze(run.events);
        Object.freeze(run);
    }
    const api = Object.freeze({ step: 1 / 120, runs: Object.freeze(runs) });
    if (typeof module !== 'undefined' && module.exports) module.exports = api;
    root.HarborVerification = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
